# docker-compose.yaml
version: '3'

services:
  app:
    extends:
      file: docker-services.yml
      service: tsd
  db:
    extends:
      file: docker-services.yml
      service: db
    volumes:
      - "db_data:/home/postgres/pgdata/data"
  pgadmin:
    extends:
      file: docker-services.yml
      service: pgadmin
  frontend:
    extends:
      file: docker-services.yml
      service: frontend
    depends_on:
      - app
#  grafana:
#    extends:
#      file: docker-services.yml
#      service: grafana
#    volumes:
#      - "grafana-storage:/var/lib/grafana"
#  renderer:
#    extends:
#      file: docker-services.yml
#      service: renderer
volumes:
  db_data:
#  grafana-storage:
