version: '3'
services:
  db:
    build:
      context: ./docker/timescale/
    image: tsdsystem-db
    container_name: db
    restart: always
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME}"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:6.8
    restart: "unless-stopped"
    ports:
      - 5050:80
      - 5051:443
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - ./docker/timescale/servers.json:/pgadmin4/servers.json
  grafana:
    image: grafana/grafana-oss:8.4.5
    ports:
    - 3000:3000
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
    - 8081
