version: '3'
services:
  tsd:
    build:
      context: ./docker/php/
    image: tsdsystem-app
    container_name: app
    tty: true
    depends_on:
      - db
    environment:
      DB_HOST: "${DB_HOST}"
      DB_USER: "${TSD_DB_USER}"
      DB_PASSWORD: "${TSD_DB_PASSWORD}"
      DB_NAME: "${TSD_DB}"
      DB_PORT: "${DB_PORT}"
      SERVER_KEY: "${SERVER_KEY}"
      APP_ALLOWED_HOSTS: "${APP_ALLOWED_HOSTS}"
      ADMIN_ID: "${ADMIN_ID}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
    working_dir: /var/www/html/tsdws
    volumes:
      - ./src:/var/www/html
  db:
    image: timescale/timescaledb-ha:pg14.2-ts2.6.0-oss-latest
    container_name: db
    restart: always
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_USER}"
    ports:
      - "5432:5432"
  frontend:
    build: ./docker/nginx/
    restart: "unless-stopped"
    ports:
      - "80:80"
      - "443:443"
  pgadmin:
    image: dpage/pgadmin4:6.8
    restart: "unless-stopped"
    ports:
      - 5050:80
      - 5051:443
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - ./docker/timescale/servers.json:/pgadmin4/servers.json
  grafana:
    image: grafana/grafana-oss:8.4.5
    ports:
    - 3000:3000
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000
      GF_LOG_FILTERS: rendering:debug
      # GF_USERS_ALLOW_SIGN_UP: false
      GF_SERVER_DOMAIN: grafana:3000
      GF_SERVER_ROOT_URL: ${PUBLIC_URL}/grafana/
      GF_SERVER_SERVE_FROM_SUB_PATH: true
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_password
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
    - 8081
