# docker-compose.yaml
version: '3'

services:
  app:
    extends:
      file: docker-services.yml
      service: tsd
    ports:
      - "8000:80"
  db:
    extends:
      file: docker-services.yml
      service: db
    volumes:
      - "db_data:/home/postgres/pgdata/data"
volumes:
  db_data:
