# docker-compose.yaml
version: '3'

services:
  app:
    build:
      context: ./docker/php/
    image: tsdsystem-app
    container_name: app
    tty: true
    depends_on:
      - db
    environment:
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_PORT: "${DB_PORT}"
      SERVER_KEY: "${SERVER_KEY}"
    ports:
      - "8000:80"
    working_dir: /var/www/html/tsdws
    volumes:
      - ./src:/var/www/html
  db:
    extends:
      file: docker-services.yml
      service: db
    volumes:
      - "db_data:/home/postgres/pgdata/data"
volumes:
  db_data:
