CREATE EXTENSION IF NOT EXISTS postgis CASCADE;

CREATE SCHEMA IF NOT EXISTS tsd_pnet AUTHORIZATION webapp_user;
CREATE SCHEMA IF NOT EXISTS tsd_main AUTHORIZATION webapp_user;
CREATE SCHEMA IF NOT EXISTS tsd_users AUTHORIZATION webapp_user;