name: Publish Docker Images

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - image_name: tsdsystem-app
            context: .
            dockerfile: ./docker/php/Dockerfile.prod
          - image_name: tsdsystem-db
            context: ./docker/timescale
            dockerfile: ./docker/timescale/Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: gh-actions

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine image tag
        id: tag
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/master ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push ${{ matrix.image_name }}
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.image_name }}:${{ steps.tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Run ${{ matrix.image_name }}
        run: |
          docker run --rm -d ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.image_name }}:${{ steps.tag.outputs.tag }}

      - name: Logout from Docker Registry
        if: always()
        run: docker logout ${{ env.REGISTRY }}